[package]
name = "vetta_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
infer.workspace = true
thiserror.workspace = true
serde.workspace = true
